run:
    preprocess: True         # If flag is passed, the ASTs will be re-generated. Otherwise, the script will load pre-generated AST
    verbose: True
paths:
    datadir: "../data"       # Path to the top level data directory.
    name: "youtube-dl-example"      # Identifier for the mined directory.
    folder: "youtube-dl"            # Raw code folder identifier.
    pregenpath: "AST"        # Pre-generated AST folder identifier.
experiment:
    train_ratio: 0.8         # At a file level, fraction of training samples
    val_ratio: 0.2           # At a file level, fraction of validation samples
    graph_type: "project_graph" # Graph granularity level ("file_graph" for one graph per file, "project_graph" for one large graph)
    train_files: ['lib/ansible']          # Directory of files to build the training graph(s) from
    test_files: ['examples']        # Directory of files to build the test graph(s) from
    dense: False 
